#Exploratory Data Analysis: Popularity of Disney Princess

[Disney Princess Popularity Dataset](https://www.kaggle.com/datasets/hamnakaleemds/disney-princess-popularity-dataset/data)

##Load the DataSet

In [66]:
#Kaggle library
import kagglehub
# Download latest version
path = kagglehub.dataset_download("hamnakaleemds/disney-princess-popularity-dataset")
#Print the path of the dataset
print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/disney-princess-popularity-dataset

In [67]:
#Import the libraries
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

##Analysis of Data

In [68]:
#read the file
df=pd.read_csv(path+"/disney_princess_popularity_dataset_300_rows.csv")
#show the first five rows
df.head()

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
0,Pocahontas,Pocahontas's Adventure,1977,85,4,No,Yes,Brown,Green,Pink,...,88,661,25,2524,68,298,481,#TeamPocahontas #LovePocahontas #PocahontasFor...,Yes,88
1,Mulan,Mulan's Adventure,1995,85,1,Yes,Yes,Blonde,Brown,Purple,...,91,688,52,4202,49,133,619,#TeamMulan #LoveMulan #MulanForever,Yes,78
2,Raya,Raya's Adventure,1989,110,4,No,No,Blonde,Hazel,Pink,...,76,790,54,525,68,129,230,#TeamRaya #LoveRaya #RayaForever,No,53
3,Anna,Anna's Adventure,1940,78,1,No,No,Brown,Grey,Green,...,70,820,42,1951,73,138,697,#TeamAnna #LoveAnna #AnnaForever,Yes,84
4,Mulan,Mulan's Adventure,1943,103,7,No,Yes,White,Brown,Green,...,86,996,55,3958,34,155,200,#TeamMulan #LoveMulan #MulanForever,Yes,71

In [5]:
# Show the last five rows
df.tail()

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
295,Merida,Merida's Adventure,2001,95,7,Yes,No,Red,Grey,Purple,...,89,309,49,3638,98,225,881,#TeamMerida #LoveMerida #MeridaForever,No,95
296,Belle,Belle's Adventure,2006,76,1,Yes,No,Red,Green,Yellow,...,97,406,53,1558,33,270,274,#TeamBelle #LoveBelle #BelleForever,No,96
297,Anna,Anna's Adventure,2020,70,2,No,Yes,White,Blue,Blue,...,72,935,25,1815,53,53,164,#TeamAnna #LoveAnna #AnnaForever,Yes,67
298,Tiana,Tiana's Adventure,1937,71,7,No,No,Red,Blue,Purple,...,86,463,54,2365,35,116,584,#TeamTiana #LoveTiana #TianaForever,No,76
299,Mulan,Mulan's Adventure,1938,105,3,No,No,Brown,Brown,Purple,...,77,195,42,2218,89,11,540,#TeamMulan #LoveMulan #MulanForever,No,69

In [5]:
#Ask for the shape of the dataset
df.shape
#300 rows and 36 columns

(300, 36)

In [6]:
#show the info of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PrincessName                300 non-null    object
 1   FirstMovieTitle             300 non-null    object
 2   FirstMovieYear              300 non-null    int64
 3   MovieRuntimeMinutes         300 non-null    int64
 4   NumberOfSongs               300 non-null    int64
 5   HasSoloSong                 300 non-null    object
 6   HasDuet                     300 non-null    object
 7   HairColor                   300 non-null    object
 8   EyeColor                    300 non-null    object
 9   OutfitPrimaryColor          300 non-null    object
 10  OutfitStyleEra              300 non-null    object
 11  IsRoyalByBirth              300 non-null    object
 12  HasAnimalSidekick           300 non-null    object
 13  SidekickType                230 non-null    object
 14  HasMagicalPowers            300 non-null    object
 15  MagicType                   247 non-null    object
 16  MainSetting                 300 non-null    object
 17  IsBasedOnRealStory          300 non-null    object
 18  CulturalOrigin              300 non-null    object
 19  SpeaksToAnimals             300 non-null    object
 20  FightsVillainDirectly       300 non-null    object
 21  RomanticSubplot             300 non-null    object
 22  MarriedByEnd                300 non-null    object
 23  VillainName                 300 non-null    object
 24  VillainType                 253 non-null    object
 25  IMDB_Rating                 300 non-null    float64
 26  RottenTomatoesScore         300 non-null    int64
 27  BoxOfficeMillions           300 non-null    int64
 28  AvgScreenTimeMinutes        300 non-null    int64
 29  NumMerchItemsOnAmazon       300 non-null    int64
 30  GoogleSearchIndex2024       300 non-null    int64
 31  InstagramFanPages           300 non-null    int64
 32  TikTokHashtagViewsMillions  300 non-null    int64
 33  Top3Hashtags                300 non-null    object
 34  IsIconic                    300 non-null    object
 35  PopularityScore             300 non-null    int64
dtypes: float64(1), int64(11), object(24)
memory usage: 84.5+ KB

In [7]:
#show a general analysis of the dataset
df.describe()

,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,IMDB_Rating,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,PopularityScore
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,1980.243333,90.913333,3.993333,7.466667,80.650000,700.843333,40.616667,2467.270000,61.300000,152.063333,506.870000,75.130000
std,24.621227,11.726502,2.149890,0.863311,10.996237,346.922618,11.575680,1469.301225,22.393785,83.929214,292.751278,14.293382
min,1937.000000,70.000000,1.000000,6.000000,60.000000,101.000000,20.000000,61.000000,20.000000,10.000000,10.000000,50.000000
25%,1959.750000,80.000000,2.000000,6.700000,71.750000,392.000000,31.750000,1223.500000,41.750000,75.750000,236.500000,63.000000
50%,1983.000000,91.000000,4.000000,7.400000,80.000000,709.500000,41.000000,2357.500000,61.000000,148.500000,524.500000,75.000000
75%,2000.250000,101.000000,6.000000,8.200000,90.000000,997.250000,51.000000,3743.250000,81.000000,227.250000,781.250000,87.000000
max,2021.000000,110.000000,7.000000,9.000000,100.000000,1300.000000,60.000000,4998.000000,100.000000,300.000000,999.000000,100.000000

In [8]:
#count the number of duplicate rows
df.duplicated().sum()
#as the output is 0, the dataset hasn't duplicate rows

np.int64(0)

In [9]:
#count the number of null values by column
df.isnull().sum()

PrincessName                   0
FirstMovieTitle                0
FirstMovieYear                 0
MovieRuntimeMinutes            0
NumberOfSongs                  0
HasSoloSong                    0
HasDuet                        0
HairColor                      0
EyeColor                       0
OutfitPrimaryColor             0
OutfitStyleEra                 0
IsRoyalByBirth                 0
HasAnimalSidekick              0
SidekickType                  70
HasMagicalPowers               0
MagicType                     53
MainSetting                    0
IsBasedOnRealStory             0
CulturalOrigin                 0
SpeaksToAnimals                0
FightsVillainDirectly          0
RomanticSubplot                0
MarriedByEnd                   0
VillainName                    0
VillainType                   47
IMDB_Rating                    0
RottenTomatoesScore            0
BoxOfficeMillions              0
AvgScreenTimeMinutes           0
NumMerchItemsOnAmazon          0
GoogleSearchIndex2024          0
InstagramFanPages              0
TikTokHashtagViewsMillions     0
Top3Hashtags                   0
IsIconic                       0
PopularityScore                0
dtype: int64

Here we can see that just 3 columns have null values (Sidekick Type, Magic Type, Villian Type)

##Preparation and Cleaning of Data

In [6]:
#Here we change the null values with an 'Unspecified'
#as the columns with null values are categorical variables is functional this change
df.fillna('Unspecified', inplace=True)

In [7]:
# This sorts by type of data
df.dtypes.sort_values()

PopularityScore                 int64
RottenTomatoesScore             int64
BoxOfficeMillions               int64
NumMerchItemsOnAmazon           int64
GoogleSearchIndex2024           int64
InstagramFanPages               int64
AvgScreenTimeMinutes            int64
NumberOfSongs                   int64
MovieRuntimeMinutes             int64
FirstMovieYear                  int64
TikTokHashtagViewsMillions      int64
IMDB_Rating                   float64
FightsVillainDirectly          object
Top3Hashtags                   object
VillainType                    object
VillainName                    object
MarriedByEnd                   object
RomanticSubplot                object
SpeaksToAnimals                object
PrincessName                   object
IsIconic                       object
MainSetting                    object
MagicType                      object
HasMagicalPowers               object
SidekickType                   object
HasAnimalSidekick              object
IsRoyalByBirth                 object
OutfitStyleEra                 object
OutfitPrimaryColor             object
EyeColor                       object
HairColor                      object
HasDuet                        object
HasSoloSong                    object
FirstMovieTitle                object
CulturalOrigin                 object
IsBasedOnRealStory             object
dtype: object

 It makes it possible to identify the type of variables that we have in each column

* The columns of **int64** and **float64** types, are variables of numerical type.

* The columns of **object** type, are categorical variables.

In [8]:
#First, we will separate the variables categoricals and numericals'
#Make a copy with the numerical variables
numericals_var=df.select_dtypes(include=['int64','float64'])
#Add the column Princess Name
numericals_var['PrincessName']=df['PrincessName']
numericals_var.head()

,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,IMDB_Rating,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,PopularityScore,PrincessName
0,1977,85,4,7.7,88,661,25,2524,68,298,481,88,Pocahontas
1,1995,85,1,6.3,91,688,52,4202,49,133,619,78,Mulan
2,1989,110,4,6.3,76,790,54,525,68,129,230,53,Raya
3,1940,78,1,8.8,70,820,42,1951,73,138,697,84,Anna
4,1943,103,7,7.9,86,996,55,3958,34,155,200,71,Mulan

In [9]:
#Make a copy of the categorical variables
categoricals_var=df.select_dtypes(include=['object'])
categoricals_var.head()

,PrincessName,FirstMovieTitle,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,OutfitStyleEra,IsRoyalByBirth,HasAnimalSidekick,...,IsBasedOnRealStory,CulturalOrigin,SpeaksToAnimals,FightsVillainDirectly,RomanticSubplot,MarriedByEnd,VillainName,VillainType,Top3Hashtags,IsIconic
0,Pocahontas,Pocahontas's Adventure,No,Yes,Brown,Green,Pink,Victorian,Yes,Yes,...,Yes,Scottish,No,Yes,No,No,Villain of Pocahontas,Witch,#TeamPocahontas #LovePocahontas #PocahontasFor...,Yes
1,Mulan,Mulan's Adventure,Yes,Yes,Blonde,Brown,Purple,Ancient,No,Yes,...,Yes,Native American,Yes,Yes,Yes,Yes,Villain of Mulan,Stepmother,#TeamMulan #LoveMulan #MulanForever,Yes
2,Raya,Raya's Adventure,No,No,Blonde,Hazel,Pink,Victorian,Yes,Yes,...,Yes,Polynesian,No,Yes,No,Yes,Villain of Raya,Witch,#TeamRaya #LoveRaya #RayaForever,No
3,Anna,Anna's Adventure,No,No,Brown,Grey,Green,Ancient,No,Yes,...,No,Scottish,No,No,No,No,Villain of Anna,Witch,#TeamAnna #LoveAnna #AnnaForever,Yes
4,Mulan,Mulan's Adventure,No,Yes,White,Brown,Green,Modern,Yes,No,...,Yes,Arabian,No,No,Yes,No,Villain of Mulan,Sorcerer,#TeamMulan #LoveMulan #MulanForever,Yes

##Analysis and Visualization

###Numerical Variables

In [15]:
#This line show the unique values of the column of Princess Name
df['PrincessName'].unique()

array(['Pocahontas', 'Mulan', 'Raya', 'Anna', 'Jasmine', 'Snow White',
       'Rapunzel', 'Belle', 'Cinderella', 'Ariel', 'Elsa', 'Aurora',
       'Moana', 'Tiana', 'Merida'], dtype=object)

First, I ask for the name of the princess that we have on the dataset, because we need have a preview of the posibles results

In [16]:
df['PrincessName'].value_counts()

PrincessName
Mulan         29
Raya          23
Anna          23
Moana         22
Cinderella    21
Merida        21
Belle         20
Ariel         20
Pocahontas    19
Snow White    18
Rapunzel      18
Aurora        18
Jasmine       17
Elsa          16
Tiana         15
Name: count, dtype: int64

Mulan is the princess with more rows in this dataset, however we could thinking that is a fact of Popularity but with this analysis dont have a high score of Popularity.

In [17]:
#Here we show the popularity score and the princess's name in a descending order
df[['PrincessName','PopularityScore']].sort_values(by='PopularityScore', ascending=False).head(10)

    PrincessName  PopularityScore
277       Aurora              100
276        Mulan              100
243        Ariel              100
129        Ariel              100
72         Moana              100
108        Tiana              100
191         Raya               99
61        Merida               99
139        Ariel               99
271   Pocahontas               99

We can notice that many have the same score, so we will calculate the popularity using other facts, such as the Number of MerchItems on Amazon, the BoxOffice data, and other numerical variables, that will be meaning, it give us a clear number of their results in the daata set, so we group the values by the Princess Name coincidence.

In [70]:
#We define the columns that won't be used
DontUse=['FirstMovieYear','MovieRuntimeMinutes','NumberOfSongs']
#First, drop the columns in the array
#calculamos el promedio por columna y agrupamos segun el nombre de la princesa
Popularity=numericals_var.drop(columns=DontUse).groupby('PrincessName').mean()
Popularity.head()

,IMDB_Rating,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,PopularityScore
PrincessName,,,,,,,,,
Anna,7.673913,82.391304,825.478261,40.260870,1934.217391,60.739130,149.347826,374.826087,72.739130
Ariel,7.490000,81.150000,695.100000,40.500000,2551.450000,58.750000,159.750000,528.450000,76.150000
Aurora,7.616667,82.833333,755.277778,41.277778,2491.333333,59.611111,171.111111,528.666667,73.555556
Belle,8.000000,81.000000,719.800000,39.800000,2313.900000,60.450000,112.350000,472.950000,79.950000
Cinderella,7.276190,81.380952,619.047619,40.428571,2392.523810,63.428571,153.428571,515.095238,75.952381

In [43]:
#We create a cycle that repeat the process of create and show the plot
#This cycle is repeated the number ofr columns before the last one
for column in Popularity.columns[:-1]:
  #create the plot of bar with the column and the Precess's Name
    fig = px.bar(Popularity, x=column, y="PrincessName", color="PrincessName")
  #show the plot
    fig.show()

These graphs show a discrepancy, because the previous plot shows that Princess Elsa have the highest mean of score popularity and before when we present the highers scores dont have a enough score.

In [79]:
#create arrays for save the max values
Popularity.reset_index(inplace=True)
#create the arrays
columns= []
princess= []
values= []
#create a cycle that will repeated the same times as columns
for column in Popularity.columns:
  #Ask for skip th column 'PrincessName'
    if column != 'PrincessName':
      #Ask the maximum value
        maxValue= Popularity[column].max()
        #save the princess's name of the max value in this column
        maxPrincess= Popularity[Popularity[column] == maxValue]['PrincessName'].values
        #add to the arrays
        columns.append(column)
        princess.append(maxPrincess)
        values.append(maxValue)
#create a dataframe with the arrays
MaxPopularity= pd.DataFrame({'Column': columns, 'PrincessName': princess, 'Value': values})
#set the column 'Column' as the index
MaxPopularity.set_index('Column', inplace=True)
MaxPopularity

                            PrincessName        Value
Column
IMDB_Rating                      [Belle]     8.000000
RottenTomatoesScore              [Tiana]    83.133333
BoxOfficeMillions              [Jasmine]   866.823529
AvgScreenTimeMinutes        [Snow White]    45.611111
NumMerchItemsOnAmazon            [Tiana]  2941.400000
GoogleSearchIndex2024            [Moana]    68.681818
InstagramFanPages               [Merida]   183.285714
TikTokHashtagViewsMillions     [Jasmine]   598.117647
PopularityScore                   [Elsa]    81.750000

We can see that several princesses have the maximum in various factors, to determine which princess is the most popular, we decided to average all the columns for have a more specific score of popularity.

In [84]:
#We create a new column that save the mean of all the row (axis=1)
Popularity.drop(columns='PrincessName', inplace=True)
Popularity['MeanScoresPopularity']=Popularity.mean(axis=1)
Popularity.head()

,IMDB_Rating,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,PopularityScore,MeanScoresPopularity
0,7.673913,82.391304,825.478261,40.260870,1934.217391,60.739130,149.347826,374.826087,72.739130,394.185990
1,7.490000,81.150000,695.100000,40.500000,2551.450000,58.750000,159.750000,528.450000,76.150000,466.532222
2,7.616667,82.833333,755.277778,41.277778,2491.333333,59.611111,171.111111,528.666667,73.555556,467.920370
3,8.000000,81.000000,719.800000,39.800000,2313.900000,60.450000,112.350000,472.950000,79.950000,432.022222
4,7.276190,81.380952,619.047619,40.428571,2392.523810,63.428571,153.428571,515.095238,75.952381,438.729101

In [46]:
#First we sort the values
Popularity_plot=Popularity.sort_values(by='MeanScoresPopularity').reset_index()
#we create the plot and give as variables the Name of the princess and the mean of popularity
fig = px.bar( Popularity_plot,x='PrincessName',y='MeanScoresPopularity',
             color='PrincessName',title='Average of Popularity by Princess')
fig.show()

In [85]:
#Calculate the standard deviation
std_por_columna = Popularity.std()
std_por_columna

IMDB_Rating                     0.293993
RottenTomatoesScore             1.734737
BoxOfficeMillions             100.456921
AvgScreenTimeMinutes            2.439708
NumMerchItemsOnAmazon         291.230159
GoogleSearchIndex2024           3.454038
InstagramFanPages              20.700511
TikTokHashtagViewsMillions     57.278404
PopularityScore                 3.893409
MeanScoresPopularity           38.057852
dtype: float64

At first sight there is no great separation between the scores, but when we calculate the standar deviation between the columns is clear that columns as NumMerchItemsOnAmazon (Number of MerchItems in Amazon), BoxOfficeMillions (MIllion of BoxOffice) are the columns where we have more difference between Princesses.

In [42]:
#Create the plot for standard deviation
fig = px.bar(std_por_columna, x=std_por_columna.index, y=std_por_columna.values,
             color=std_por_columna.index)
fig.show()

All the columns have a relative influence in the Popularity of Princess.

In [47]:
#We normalized the dataframe for after make a heatmap and not have a big difference in numbers
PopularityNormal=(Popularity-Popularity.min())/(Popularity.max()-Popularity.min())
#then sort by score of popularity
PopularityNormal=PopularityNormal.sort_values(by='MeanScoresPopularity')
PopularityNormal.head()

,IMDB_Rating,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,PopularityScore,MeanScoresPopularity
PrincessName,,,,,,,,,,
Anna,0.754206,0.881294,0.878056,0.466691,0.000000,0.373695,0.570542,0.000000,0.349917,0.000000
Pocahontas,0.738165,0.675560,0.096759,0.000000,0.086791,0.659875,0.702007,0.828585,0.778821,0.018169
Merida,0.511845,0.567306,0.530019,0.435941,0.183654,0.232804,1.000000,0.684702,0.791297,0.215897
Elsa,0.378141,0.668719,0.456723,0.727266,0.380177,0.290771,0.506823,0.410277,1.000000,0.283353
Belle,1.000000,0.658720,0.566367,0.420752,0.376975,0.350896,0.102362,0.439443,0.870140,0.287704

In [48]:
#We create a heatmap for a best visualitation of the Popularity Socre
fig = px.imshow(PopularityNormal*100, labels=dict(x="Facts", y="Princess Name", color="Popularity %"), aspect="auto")
fig.show()

In this heatmap we can see more clearly the columns that give to each princess her score and why Tiana have the most highest score because she have a higher score in RottenTomatoScore and NumMerchItemsOnAmazon.

###Categorical Variables

When we see the categorical variables, we select some variables that could be interesting to analysis if have relation with the score Popularity.

When we think in Disney Princess, we have a set of diferents culturs and I think this is the reason that have many Popularity, because we can identify with these princesses.

In [56]:
#Save the values of cultural origin
culturals=categoricals_var['CulturalOrigin'].unique()
#Count the times that was repeated a value
count=categoricals_var['CulturalOrigin'].value_counts()
#create a data frame with the values and the number of times
culturalcount=pd.DataFrame({'culturals':culturals,'count':count})
#create a plot
fig= px.pie(culturalcount, values='count', names='culturals')
fig.show()

Don't have a big difference between culturs of origin, but the Scottish culture is in the top with 14.7% (44 princesses), just.7% over Native American princesses and in the bottom with a 10% (30 princesses) the French culture origin.

With this results the Outfit Style could be relationed, this is for we decide include this pie graph.

In [64]:
#As the previous, ask for the values of this column
outfit=categoricals_var['OutfitStyleEra'].unique()
#COunt the timas that the value was repeated
count=categoricals_var['OutfitStyleEra'].value_counts()
#create a dataframe with the values and the times
oufitcount=pd.DataFrame({'outfit':outfit,'count':count})
#create a plot
fig= px.pie(oufitcount, values='count', names='outfit')
fig.show()

The Victorian Era is in the top with 29.7% (89 princesses) and the Medieval Era in the bottom with 22% (86 princesses), 3 princesses isn't a big diference.

The relationship between popularity score and some characteristics like whether a princess has a solo song could give us insight into how these categorical variables influence a character's popularity.

In [25]:
#we add the score popularity to the categorical's variables because we want found a relation in both variables
categoricals_var['ScorePopularity']=df['PopularityScore']
#first we found the maximum score and save it
maxscore=categoricals_var['ScorePopularity'].max()
#then we search all the results with the same score
bymaxScore=categoricals_var[categoricals_var['ScorePopularity']==maxscore]
bymaxScore

,PrincessName,FirstMovieTitle,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,OutfitStyleEra,IsRoyalByBirth,HasAnimalSidekick,...,CulturalOrigin,SpeaksToAnimals,FightsVillainDirectly,RomanticSubplot,MarriedByEnd,VillainName,VillainType,Top3Hashtags,IsIconic,ScorePopularity
72,Moana,Moana's Adventure,Yes,Yes,White,Brown,Purple,Modern,No,Yes,...,Nordic,Yes,No,No,No,Villain of Moana,Warlord,#TeamMoana #LoveMoana #MoanaForever,Yes,100
108,Tiana,Tiana's Adventure,No,Yes,Blonde,Hazel,Blue,Modern,No,No,...,French,Yes,No,Yes,No,Villain of Tiana,Stepmother,#TeamTiana #LoveTiana #TianaForever,Yes,100
129,Ariel,Ariel's Adventure,Yes,No,White,Grey,Purple,Medieval,Yes,Yes,...,French,No,Yes,No,No,Villain of Ariel,Warlord,#TeamAriel #LoveAriel #ArielForever,Yes,100
243,Ariel,Ariel's Adventure,Yes,No,Blonde,Green,Purple,Ancient,No,Yes,...,African-American,Yes,No,No,No,Villain of Ariel,Witch,#TeamAriel #LoveAriel #ArielForever,Yes,100
276,Mulan,Mulan's Adventure,No,Yes,Black,Green,Purple,Ancient,Yes,No,...,Chinese,No,No,Yes,Yes,Villain of Mulan,Sorcerer,#TeamMulan #LoveMulan #MulanForever,Yes,100
277,Aurora,Aurora's Adventure,Yes,No,White,Blue,Pink,Victorian,No,Yes,...,Native American,No,Yes,Yes,Yes,Villain of Aurora,Hunter,#TeamAurora #LoveAurora #AuroraForever,No,100

Here we have the rows with the highest score, so we will compare with variables like HasSoloSong, IsRoyalByBirth, HasMagicalPowers, IsBasedOnRealStory, SpeaksToAnimals, MarriedByEnd;
We think that those are characteristics that could give us interesting information.

In [43]:
#Define the columns that we will analysis
CategoricalBinary=bymaxScore[['HasSoloSong', 'IsRoyalByBirth',
                                   'HasMagicalPowers','IsBasedOnRealStory',
                                   'SpeaksToAnimals','MarriedByEnd']]
#create a figure with 6 subplots (2*3)
fig= make_subplots(rows=2, cols=3, subplot_titles=CategoricalBinary.columns)
#Make a cycle for repeat the number of columns
for i,column in enumerate(CategoricalBinary[:6]):
  #This asign a number of row and columns
  row = (i // 3) + 1
  col = (i % 3) + 1
  #We count the number of times that a value was repeated in the maximum results previous
  count = bymaxScore[column].value_counts().reset_index()
  #Asign to the dataframe the values
  count.columns = [column, 'Count']
  #Create a plot with the data of the dataframe
  bar = go.Bar(x=count[column], y=count['Count'], name=column)
  #Asign to the figure the plot with they respective rows and columns
  fig.add_trace(bar, row=row, col=col)
fig.show()

* In the IsBasedOnRealStory and SpeaksToAnimals plots, we don't have information because there is a coincidence (the same number of princesses) in both classifications.

* In the HasMagicalPowers plot we have a bias to the Princesses that have Powers.
*  In the HasSoloSong, IsRoyalByBirt and MarriedByEnd plots we have a negative inclination, so we can't take this as a fact of influence.

In the same way, we want to compare with the minimum score, so we prepare the sames columns and the ScorePopularity.

In [28]:
#Ask for the minimum score
minscore=categoricals_var['ScorePopularity'].min()
#Save the rows with the minimum score
byminScore=categoricals_var[categoricals_var['ScorePopularity']==minscore]
byminScore

,PrincessName,FirstMovieTitle,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,OutfitStyleEra,IsRoyalByBirth,HasAnimalSidekick,...,CulturalOrigin,SpeaksToAnimals,FightsVillainDirectly,RomanticSubplot,MarriedByEnd,VillainName,VillainType,Top3Hashtags,IsIconic,ScorePopularity
71,Rapunzel,Rapunzel's Adventure,No,No,Blonde,Grey,Pink,Ancient,Yes,Yes,...,Chinese,Yes,No,Yes,No,Villain of Rapunzel,Warlord,#TeamRapunzel #LoveRapunzel #RapunzelForever,No,50
248,Rapunzel,Rapunzel's Adventure,No,Yes,Blonde,Green,Green,Modern,No,No,...,Polynesian,No,Yes,No,Yes,Villain of Rapunzel,Witch,#TeamRapunzel #LoveRapunzel #RapunzelForever,Yes,50

In [86]:
#Define the columns that we will analyze
CategoricalBinary=byminScore[['HasSoloSong', 'IsRoyalByBirth',
                                   'HasMagicalPowers','IsBasedOnRealStory',
                                   'SpeaksToAnimals','MarriedByEnd']]
#Create a figure where we will show the 6 subplots (2*3)
fig= make_subplots(rows=2, cols=3, subplot_titles=CategoricalBinary.columns)
#Create a cycle for the number of columns
for i,column in enumerate(CategoricalBinary[:6]):
  #This asign a number of row and columns
  row = (i // 3) + 1
  col = (i % 3) + 1
  #here, count the number of times that is repeated th values
  count = byminScore[column].value_counts().reset_index()
  #Add to a dataframe the values
  count.columns = [column, 'Count']
  #create a plot with the dataframe values
  bar = go.Bar(x=count[column], y=count['Count'], name=column)
  #Asign to the figure the plot with they repsective rows and columns
  fig.add_trace(bar, row=row, col=col)
fig.show()

In this case:
* The HasSoloSong and IsBasedOnRealStory plots say that this aspects are not a positive factor for popularity
* IsRoyalByBirth, HasMagicalPowers, SpeaksToAnimals and MarriedByEnd  plots don´t give us specific information because have the same influence.

Forthemore, we can get the most popular color in Princess´s dresses of this dataset.

In [45]:
#Ask for the colors of dresses
categoricals_var['OutfitPrimaryColor'].unique()

array(['Pink', 'Purple', 'Green', 'Blue', 'Yellow'], dtype=object)

In [50]:
#Ask for the times that a color is repeated
categoricals_var['OutfitPrimaryColor'].value_counts()

OutfitPrimaryColor
Yellow    68
Pink      67
Green     60
Purple    56
Blue      49
Name: count, dtype: int64

In [89]:
#create a dataframe for save the frequency
colors=pd.DataFrame()
#calculate the absolute frequency of each color
colors['frquencyA']=categoricals_var['OutfitPrimaryColor'].value_counts()
#calculate the relative frequency of each color
colors['frquencyR']=colors['frquencyA']/colors['frquencyA'].sum()
colors

                    frquencyA  frquencyR
OutfitPrimaryColor
Yellow                     68   0.226667
Pink                       67   0.223333
Green                      60   0.200000
Purple                     56   0.186667
Blue                       49   0.163333

In [94]:
#calculate the standard dispersion of the absolute frequency
stdcolors=colors['frquencyA'].std()
stdcolors

7.905694150420948

Here we can notice that this data have a standard dispersion of 7.9056, this represent that we have a diference in color about 7 princesses.

In [91]:
Mode=categoricals_var['OutfitPrimaryColor'].mode()
Mode

0    Yellow
Name: OutfitPrimaryColor, dtype: object

Then we get the most popular color, which is Yellow with 68 princesses. We could say that this is the most popular color, but we want to compare with the highest score.

In [118]:
#We take the dataframe with the maximum score and ask for the values and the ccount of values
color = bymaxScore['OutfitPrimaryColor'].value_counts().reset_index()
#Asign the name of columns
color.columns = ['OutfitPrimaryColor', 'counts']
#create the plot with the dataframe data
fig = px.bar(color,x='OutfitPrimaryColor', y='counts', color='OutfitPrimaryColor')
fig.show()

Here we can see that in relation with the highest Score of Popularity the most popular color of dress is Purple.

##Conclusions

In this Analysis, we can get different information, and in this section we will sumarize the most relevant information that we got in the dataset.

**Numerical Variables**

* Although Mulan is the princess with most repetitions, when we grouped by princess, we find that Princess Elsa has the highest Score popularity.
However, when we calculate our own popularity score considering the other columns, the winning princess turns out to be Tiana.

**Categorical Variables**
* We found an equilibrate variable about the origin.

    > Don't have a big difference between culturs of origin, but the Scottish culture is in the top with 14.7% (44 princesses), just.7% over Native American princesses and in the bottom with a 10% (30 princesses) the French culture origin.


* We might think that Disney princess movies have a big difference in the eras in which they are set, but the clothing tells us that there is a certain balance between the Eras.

    > The Victorian Era is in the top with 29.7% (89 princesses) and the Medieval Era in the bottom with 22% (86 princesses), 3 princesses isn't a big diference.

**Relation beetween charactheristics and Popularity Score**
* According to the analysis of the maximum scores, we can see that if a princess has powers, her popularity score increases, which may be due to it being a great ability that not everyone has.
    >In the HasMagicalPowers plot we have a bias to the Princesses that have Powers.

* When comparing the highest values, we can see that the fact that a princess does not have songs alone, whether she is a princess by birth or is married at the end, are factors that do not intervene in her popularity.

    >In the HasSoloSong, IsRoyalByBirth and MarriedByEnd plots we have a negative inclination, so we can't take this as a fact of influence.

*When we ask which is the most repeated color, the result is yellow; however, when comparing it with the highest score, the clear winner is purple.

Of this information we can take decision as make more products of the most popular Princess that was Tiana or could be help for the Disney corporation when they create new movies, because they can consider the same characteristics that the princesses more populars.



---



    Dataset Information

    Name: Disney Princess Popularity Dataset

    Link: https://www.kaggle.com/datasets/hamnakaleemds/disney-princess-popularity-dataset/data
Santillan Nuñez Ana Paula - 246102